// Code generated by protoc-gen-go. DO NOT EDIT.
// source: score_info.proto

package score_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//*
// @brief base_score_info
type BaseScoreInfoT struct {
	WinCount             int32    `protobuf:"varint,1,opt,name=win_count,json=winCount,proto3" json:"win_count,omitempty"`
	LoseCount            int32    `protobuf:"varint,2,opt,name=lose_count,json=loseCount,proto3" json:"lose_count,omitempty"`
	ExceptionCount       int32    `protobuf:"varint,3,opt,name=exception_count,json=exceptionCount,proto3" json:"exception_count,omitempty"`
	KillCount            int32    `protobuf:"varint,4,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	DeathCount           int32    `protobuf:"varint,5,opt,name=death_count,json=deathCount,proto3" json:"death_count,omitempty"`
	AssistCount          int32    `protobuf:"varint,6,opt,name=assist_count,json=assistCount,proto3" json:"assist_count,omitempty"`
	Rating               int64    `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseScoreInfoT) Reset()         { *m = BaseScoreInfoT{} }
func (m *BaseScoreInfoT) String() string { return proto.CompactTextString(m) }
func (*BaseScoreInfoT) ProtoMessage()    {}
func (*BaseScoreInfoT) Descriptor() ([]byte, []int) {
	return fileDescriptor_0530380906c12eb9, []int{0}
}

func (m *BaseScoreInfoT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseScoreInfoT.Unmarshal(m, b)
}
func (m *BaseScoreInfoT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseScoreInfoT.Marshal(b, m, deterministic)
}
func (m *BaseScoreInfoT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseScoreInfoT.Merge(m, src)
}
func (m *BaseScoreInfoT) XXX_Size() int {
	return xxx_messageInfo_BaseScoreInfoT.Size(m)
}
func (m *BaseScoreInfoT) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseScoreInfoT.DiscardUnknown(m)
}

var xxx_messageInfo_BaseScoreInfoT proto.InternalMessageInfo

func (m *BaseScoreInfoT) GetWinCount() int32 {
	if m != nil {
		return m.WinCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetLoseCount() int32 {
	if m != nil {
		return m.LoseCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetExceptionCount() int32 {
	if m != nil {
		return m.ExceptionCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetKillCount() int32 {
	if m != nil {
		return m.KillCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetDeathCount() int32 {
	if m != nil {
		return m.DeathCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetAssistCount() int32 {
	if m != nil {
		return m.AssistCount
	}
	return 0
}

func (m *BaseScoreInfoT) GetRating() int64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func init() {
	proto.RegisterType((*BaseScoreInfoT)(nil), "score_server.base_score_info_t")
}

func init() { proto.RegisterFile("score_info.proto", fileDescriptor_0530380906c12eb9) }

var fileDescriptor_0530380906c12eb9 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x4d, 0xae, 0x82, 0x30,
	0x14, 0x46, 0xd3, 0xc7, 0x83, 0xf7, 0xb8, 0x10, 0x7f, 0x18, 0x18, 0x12, 0x63, 0x44, 0x27, 0x32,
	0x72, 0xe2, 0x12, 0xdc, 0x01, 0x1b, 0x68, 0x0a, 0x5e, 0xb5, 0x91, 0xb4, 0xa4, 0xad, 0xe2, 0xbe,
	0xdd, 0x80, 0xa1, 0xad, 0x38, 0xbc, 0xe7, 0x9c, 0x7c, 0x83, 0x0b, 0x33, 0xdd, 0x48, 0x85, 0x94,
	0x8b, 0xb3, 0xdc, 0x77, 0x4a, 0x1a, 0x99, 0xa5, 0x8e, 0x68, 0x54, 0x0f, 0x54, 0xdb, 0x17, 0x81,
	0x79, 0xcd, 0x34, 0xd2, 0x6f, 0x47, 0x4d, 0xb6, 0x84, 0xb8, 0xe7, 0x82, 0x36, 0xf2, 0x2e, 0x4c,
	0x4e, 0x0a, 0x52, 0x86, 0xd5, 0x7f, 0xcf, 0xc5, 0x71, 0xb8, 0xb3, 0x15, 0x40, 0x2b, 0x35, 0x7a,
	0xfb, 0x63, 0x6d, 0x3c, 0x10, 0xa7, 0x77, 0x30, 0xc5, 0x67, 0x83, 0x9d, 0xe1, 0xf2, 0xb3, 0x10,
	0xd8, 0x66, 0x32, 0xe2, 0x71, 0xe7, 0xc6, 0xdb, 0xd6, 0x37, 0xbf, 0x6e, 0x67, 0x20, 0x4e, 0xaf,
	0x21, 0x39, 0x21, 0x33, 0x57, 0xef, 0x43, 0xeb, 0xc1, 0x22, 0x17, 0x6c, 0x20, 0x65, 0x5a, 0x73,
	0x6d, 0x7c, 0x11, 0xd9, 0x22, 0x71, 0xcc, 0x25, 0x0b, 0x88, 0x14, 0x33, 0x5c, 0x5c, 0xf2, 0xbf,
	0x82, 0x94, 0x41, 0xe5, 0xaf, 0x3a, 0xb2, 0xaf, 0x38, 0xbc, 0x03, 0x00, 0x00, 0xff, 0xff, 0x9c,
	0x9d, 0xf0, 0x20, 0x1e, 0x01, 0x00, 0x00,
}
